version: '3.8'

services:
  postgres_account-service:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user_password
      POSTGRES_DB: AccountServiceDB
    ports:
      - "5432:5432"
    networks:
      net:
    volumes:
      - data_account:/var/lib/postgresql/data

  account-service:
    build: ./SimHealth
    ports:
      - "5000:80"
    networks:
      net:
    depends_on:
      - postgres_account-service
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: 80
  
  postgres_hospital-service:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user_password
      POSTGRES_DB: HospitalServiceDB
    ports:
      - "5433:5432"
    networks:
      net:
    volumes:
      - data_hospital:/var/lib/postgresql/data

  hospital-service:
    build: ./HospitalService
    ports:
      - "5001:80"
    networks:
      net:
    depends_on:
      - postgres_hospital-service
      - account-service
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: 80

  postgres_timetable-service:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user_password
      POSTGRES_DB: TimetableServiceDB
    ports:
      - "5434:5432"
    networks:
      net:
    volumes:
      - data_timetable:/var/lib/postgresql/data

  timetable-service:
    build: ./TimetableService
    ports:
      - "5002:80"
    networks:
      net:
    depends_on:
      - postgres_timetable-service
      - hospital-service
      - account-service
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: 80

  postgres_document-service:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user_password
      POSTGRES_DB: DocumentServiceDB
    ports:
      - "5435:5432"
    networks:
      net:
    volumes:
      - data_document:/var/lib/postgresql/data

  document-service:
    build: ./DocumentService
    ports:
      - "5003:80"
    networks:
      net:
    depends_on:
      - postgres_document-service
      - hospital-service
      - account-service
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: 80

volumes:
  data_account:
  data_hospital:
  data_timetable:
  data_document:
  
networks:
  net: